LIBSOLV_SRC := https://github.com/openSUSE/libsolv/archive/refs/tags/0.7.32.tar.gz

LIBSOLV_CONFIG_ARGS = -DCMAKE_INSTALL_PREFIX=$$(COSMOS)\
    -DCMAKE_PREFIX_PATH=$$(COSMOS)\
    -DCMAKE_IGNORE_PREFIX_PATH="/usr/;/usr/include"\
    -DCMAKE_FIND_ROOT_PATH=$$(COSMOS)\
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY\
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY\
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY\
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER\
    -DBUILD_SHARED_LIBS=OFF\
    -DCMAKE_BUILD_TYPE=Release\
    -DCMAKE_C_FLAGS="-Os"\
    -DCMAKE_CXX_FLAGS="-Os"\
    -DENABLE_STATIC=ON\
    -DDISABLE_SHARED=ON\
    -DENABLE_CONDA=ON\
    -DMULTI_SEMANTICS=ON\
    -DENABLE_LZMA_COMPRESSION=ON\
    -DENABLE_BZIP2_COMPRESSION=ON\
    -DENABLE_ZSTD_COMPRESSION=ON\
    -DENABLE_RPMDB=OFF\
    -DENABLE_RPMMD=OFF\
    -DENABLE_DEBIAN=OFF\
    -DWITH_LIBXML2=OFF\
    -DWITHOUT_COOKIEOPEN=ON\
    -DENABLE_STATIC_TOOLS=OFF

$(eval $(call DOWNLOAD_SOURCE,lib/libsolv,$(LIBSOLV_SRC)))
LIBSOLV_DEPS := cosmo-repo/base cosmo-repo/compress compress/xz lib/libexpat
$(eval $(call SPECIFY_DEPS,lib/libsolv,$(LIBSOLV_DEPS)))
$(eval $(call CMAKE_BUILD,lib/libsolv,$(LIBSOLV_CONFIG_ARGS),$(LIBSOLV_CONFIG_ARGS)))

o/lib/libsolv/built.fat: FATTEN_COMMAND = $(DUMMYLINK0)
